### ISSUE TITLE
the Add Dependency... dialog is not working when using the mac native look and feel

### ISSUE THREAD

**Issue by pedrohidalgo** [pedrohidalgo/pleasure#2]
java.lang.IllegalArgumentException: cannot add to layout: unknown constraint: LEFT
	at java.awt.BorderLayout.addLayoutComponent(BorderLayout.java:463)
	at java.awt.BorderLayout.addLayoutComponent(BorderLayout.java:424)
	at java.awt.Container.addImpl(Container.java:1127)
	at java.awt.Container.add(Container.java:973)
	at org.jdesktop.swingx.prompt.BuddySupport.addToComponentHierarchy(BuddySupport.java:72)
	at org.jdesktop.swingx.prompt.BuddySupport.ensureBuddiesAreInComponentHierarchy(BuddySupport.java:139)
	at org.jdesktop.swingx.plaf.TextUIWrapper$DefaultWrapper.replaceUIIfNeeded(TextUIWrapper.java:163)
	at org.jdesktop.swingx.plaf.TextUIWrapper.install(TextUIWrapper.java:49)
	at org.jdesktop.swingx.JXSearchField.setUseNativeSearchFieldIfPossible(JXSearchField.java:528)
	at org.jdesktop.swingx.JXSearchField.<init>(JXSearchField.java:178)
	at org.jdesktop.swingx.JXSearchField.<init>(JXSearchField.java:166)
	at com.qualixium.playnb.nodes.sbtdependencies.AddDependencyDialog.initComponents(AddDependencyDialog.java:60)
	at com.qualixium.playnb.nodes.sbtdependencies.AddDependencyDialog.<init>(AddDependencyDialog.java:38)
	at com.qualixium.playnb.nodes.sbtdependencies.AddDependencyAction.actionPerformed(AddDependencyAction.java:20)
	at javax.swing.AbstractButton.fireActionPerformed(AbstractButton.java:2022)
	at javax.swing.AbstractButton$Handler.actionPerformed(AbstractButton.java:2348)
	at javax.swing.DefaultButtonModel.fireActionPerformed(DefaultButtonModel.java:402)
	at javax.swing.DefaultButtonModel.setPressed(DefaultButtonModel.java:259)
	at javax.swing.AbstractButton.doClick(AbstractButton.java:376)
	at javax.swing.plaf.basic.BasicMenuItemUI.doClick(BasicMenuItemUI.java:833)
	at com.apple.laf.AquaMenuItemUI.doClick(AquaMenuItemUI.java:157)
	at javax.swing.plaf.basic.BasicMenuItemUI$Handler.mouseReleased(BasicMenuItemUI.java:877)
	at java.awt.Component.processMouseEvent(Component.java:6533)
	at javax.swing.JComponent.processMouseEvent(JComponent.java:3324)
	at java.awt.Component.processEvent(Component.java:6298)
	at java.awt.Container.processEvent(Container.java:2236)
	at java.awt.Component.dispatchEventImpl(Component.java:4889)
	at java.awt.Container.dispatchEventImpl(Container.java:2294)
	at java.awt.Component.dispatchEvent(Component.java:4711)
	at java.awt.LightweightDispatcher.retargetMouseEvent(Container.java:4888)
	at java.awt.LightweightDispatcher.processMouseEvent(Container.java:4525)
	at java.awt.LightweightDispatcher.dispatchEvent(Container.java:4466)
	at java.awt.Container.dispatchEventImpl(Container.java:2280)
	at java.awt.Window.dispatchEventImpl(Window.java:2746)
	at java.awt.Component.dispatchEvent(Component.java:4711)
	at java.awt.EventQueue.dispatchEventImpl(EventQueue.java:758)
	at java.awt.EventQueue.access$500(EventQueue.java:97)
	at java.awt.EventQueue$3.run(EventQueue.java:709)
	at java.awt.EventQueue$3.run(EventQueue.java:703)
	at java.security.AccessController.doPrivileged(Native Method)
	at java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:80)
	at java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:90)
	at java.awt.EventQueue$4.run(EventQueue.java:731)
	at java.awt.EventQueue$4.run(EventQueue.java:729)
	at java.security.AccessController.doPrivileged(Native Method)
	at java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:80)
	at java.awt.EventQueue.dispatchEvent(EventQueue.java:728)
	at org.netbeans.core.TimableEventQueue.dispatchEvent(TimableEventQueue.java:159)
[catch] at java.awt.EventDispatchThread.pumpOneEventForFilters(EventDispatchThread.java:201)
	at java.awt.EventDispatchThread.pumpEventsForFilter(EventDispatchThread.java:116)
	at java.awt.EventDispatchThread.pumpEventsForHierarchy(EventDispatchThread.java:105)
	at java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:101)
	at java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:93)
	at java.awt.EventDispatchThread.run(EventDispatchThread.java:82)

**Comment by pedrohidalgo** [comment]
The bug seems to be on the JXSearchField component, according to a conclusion someone made here: https://answers.launchpad.net/sikuli/+question/250392
